import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

const publicRoutes = [
  index("routes/home.tsx"),
  route("all", "routes/all.tsx"),
  route("items/:id", "routes/item.tsx"),
  route("items/:id/original", "routes/item-original.tsx", { id: "item-original" }),
  route("hot", "routes/hot.tsx"),
  route("story/:publicId", "routes/story.tsx"),
  route("daily", "routes/report-latest.tsx", { id: "daily-latest" }),
  route("daily/archive", "routes/daily-archive.tsx"),
  route("daily/:key", "routes/report-detail.tsx", { id: "daily-detail" }),
  route("weekly", "routes/report-latest.tsx", { id: "weekly-latest" }),
  route("weekly/:key", "routes/report-detail.tsx", { id: "weekly-detail" }),
  route("monthly", "routes/report-latest.tsx", { id: "monthly-latest" }),
  route("monthly/:key", "routes/report-detail.tsx", { id: "monthly-detail" }),
  route("topics", "routes/topics.tsx"),
  route("topics/:slug", "routes/topic.tsx", { id: "topic" }),
  route("topics/:slug/page/:page", "routes/topic.tsx", { id: "topic-page" }),
  route("about", "routes/about.tsx"),
  route("terms", "routes/terms.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("changelog", "routes/changelog.tsx"),
  route("feedback", "routes/feedback.tsx"),
  route("more", "routes/more.tsx"),
  route("starred", "routes/starred.tsx"),
  route("agent", "routes/agent.tsx"),
  route("metals", "routes/metals.tsx"),
  route("policy-threads/:id", "routes/policy-thread.tsx"),
  route("policies", "routes/policies.tsx"),
  route("policies/reports", "routes/policy-reports.tsx"),
  route("policies/reports/:id", "routes/policy-report.tsx"),
  route("policies/:id/history", "routes/policy-history.tsx"),
  route("policies/:id", "routes/policy.tsx"),
  route("*", "routes/not-found.tsx"),
] satisfies RouteConfig;

const privateRoutes = [
  route("admin/login", "routes/admin-login.tsx"),
  layout("routes/admin/layout.tsx", { id: "admin-layout" }, [
    route("admin", "routes/admin/index.tsx"),
    route("admin/content", "routes/admin/content.tsx"),
    route("admin/content/:id", "routes/admin/content-item.tsx"),
    route("admin/sources", "routes/admin/sources.tsx"),
    route("admin/sources/targets", "routes/admin/source-targets.tsx"),
    route("admin/sources/new", "routes/admin/source-new.tsx"),
    route("admin/sources/:id", "routes/admin/source.tsx"),
    route("admin/feedback", "routes/admin/feedback.tsx"),
    layout("routes/admin/usage-layout.tsx", { id: "usage-models-layout" }, [
      route("admin/usage-models", "routes/admin/models.tsx"),
      route("admin/usage-models/reconciliation", "routes/admin/reconciliation.tsx"),
      route("admin/usage-models/settings", "routes/admin/settings.tsx"),
    ]),
    route("admin/models", "routes/admin/models-redirect.tsx"),
    route("admin/settings", "routes/admin/settings-redirect.tsx"),
    route("admin/accounts", "routes/admin/accounts.tsx"),
    route("admin/account", "routes/admin/account.tsx"),
    route("admin/selectbench", "routes/admin/selectbench.tsx"),
    route("admin/selectbench/:runId", "routes/admin/selectbench-run.tsx"),
    route("admin/site", "routes/admin/site.tsx"),
  ]),
] satisfies RouteConfig;

export default process.env.WEB_ROUTE_GROUP === "private" ? privateRoutes : [layout("routes/public-layout.tsx", { id: "public-layout" }, publicRoutes)];
