// Generates the site icons in industry/brand/ (logo.svg, icon.png, icon-192.png, apple-icon.png and
// favicon.ico): the first Chinese character of the site name (industry/site.ts; 矿 for AI矿策), set in
// Noto Sans SC Black (SIL OFL 1.1) as an SVG path, white on a square in the accent colour. The colour is
// a temporary neutral placeholder (临时) until T-0006 settles the palette with the Owner (Q-67).
//
// Usage: node scripts/brand-icons.ts <@fontsource/noto-sans-sc package directory>
//   (fetch it with `npm pack @fontsource/noto-sans-sc@5.3.0` and untar; it is not a dependency)
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import opentype from "opentype.js";
import sharp from "sharp";
import { SITE } from "@amp/industry/site";

const pkg = process.argv[2];
if (!pkg) throw new Error("usage: node scripts/brand-icons.ts <noto-sans-sc package dir>");

/** 临时 (T-0006, Q-67): the light theme's placeholder accent in apps/web/app/app.css. */
const BACKGROUND = "#475569";
const INK = "#ffffff";
const SIZE = 512;
/** The character's ink, as a share of the icon's side. */
const GLYPH = 0.6;

const ch = [...SITE.name].find((c) => /\p{Script=Han}/u.test(c)) ?? SITE.name.charAt(0).toUpperCase();

// The woff slice of the 900 weight that holds the character.
const cp = ch.codePointAt(0)!;
const css = readFileSync(path.join(pkg, "900.css"), "utf8");
const face = [...css.matchAll(/url\(\.\/files\/([\w-]+)\.woff2\)[^;]*;\s*unicode-range: ([^;]+);/g)].find((m) =>
  m[2]!.split(",").some((r) => {
    const [a, b] = r
      .trim()
      .replace("U+", "")
      .split("-")
      .map((h) => parseInt(h, 16));
    return cp >= a! && cp <= (b ?? a!);
  }),
);
if (!face) throw new Error(`no slice holds ${ch}`);
const buf = readFileSync(path.join(pkg, "files", `${face[1]}.woff`));
const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));

// The ink scaled to GLYPH of the side and centred both ways.
const box = font.getPath(ch, 0, 0, 1000).getBoundingBox();
const size = (1000 * SIZE * GLYPH) / Math.max(box.x2 - box.x1, box.y2 - box.y1);
const scale = size / 1000;
const glyph = font.getPath(ch, SIZE / 2 - ((box.x1 + box.x2) / 2) * scale, SIZE / 2 - ((box.y1 + box.y2) / 2) * scale, size).toPathData(1);

const svg = (radius: number) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${SIZE} ${SIZE}"><rect width="${SIZE}" height="${SIZE}" rx="${radius}" fill="${BACKGROUND}"/><path d="${glyph}" fill="${INK}"/></svg>\n`;
const rounded = svg(112);
/** Apple rounds touch icons itself and wants them square and opaque. */
const square = svg(0);
const png = (source: string, px: number) => sharp(Buffer.from(source)).resize(px, px).png({ compressionLevel: 9 }).toBuffer();

const target = "industry/brand";
writeFileSync(`${target}/logo.svg`, `<!-- Generated by scripts/brand-icons.ts. ${ch}: Noto Sans SC Black (SIL OFL 1.1). -->\n${rounded}`);
writeFileSync(`${target}/icon.png`, await png(rounded, 512));
writeFileSync(`${target}/icon-192.png`, await png(rounded, 192));
writeFileSync(
  `${target}/apple-icon.png`,
  await sharp(await png(square, 180))
    .removeAlpha()
    .png({ compressionLevel: 9 })
    .toBuffer(),
);

// favicon.ico: 16, 32 and 48 pixel PNGs behind one icon directory.
const sizes = [16, 32, 48];
const images = await Promise.all(sizes.map((px) => png(rounded, px)));
const directory = Buffer.alloc(6 + 16 * sizes.length);
directory.writeUInt16LE(1, 2); // type: icon
directory.writeUInt16LE(sizes.length, 4);
let offset = directory.length;
sizes.forEach((px, i) => {
  const entry = 6 + 16 * i;
  directory.writeUInt8(px, entry);
  directory.writeUInt8(px, entry + 1);
  directory.writeUInt16LE(1, entry + 4); // colour planes
  directory.writeUInt16LE(32, entry + 6); // bits per pixel
  directory.writeUInt32LE(images[i]!.length, entry + 8);
  directory.writeUInt32LE(offset, entry + 12);
  offset += images[i]!.length;
});
writeFileSync(`${target}/favicon.ico`, Buffer.concat([directory, ...images]));
console.log(target, { char: ch, files: ["logo.svg", "icon.png", "icon-192.png", "apple-icon.png", "favicon.ico"] });
