// Generated by pnpm contracts:gen; do not edit.
import createClient, { type ClientOptions } from "openapi-fetch";
import type { paths } from "./private.types.ts";
export { schemas as privateSchemas } from "@amp/contracts/http/private";
export const createPrivateClient = (options: ClientOptions) => createClient<paths>(options);
