// Generated by pnpm contracts:gen; do not edit.
import createClient, { type ClientOptions } from "openapi-fetch";
import type { paths } from "./public.types.ts";
export { schemas as publicSchemas } from "@amp/contracts/http/public";
export const createPublicClient = (options: ClientOptions) => createClient<paths>(options);
